@id=4cfbb6fa-c376-478c-9542-5a63dcfe802b

PUT http://localhost:5036/breakfasts/{{id}}
Content-Type: application/json

{
  "name": "Vegan Sunshine 4",
  "description": "Vegan everything! Join us for a healthy breakfast..",
  "startDateTime": "2022-04-08T08:00:00",
  "endDateTime": "2022-04-08T11:00:00",
  "savory": ["Oatmeal", "Avocado Toast", "Omelette", "Salad"],
  "Sweet": ["Cookie"]
}